version: '3'

networks:
    nginx-php-mysql-node:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-service
            - mysql-service
        networks:
            - nginx-php-mysql-node
    # php
    php-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - nginx-php-mysql-node

    # mysql
    mysql-service:
        image: mysql:8
        container_name: mysql-container
        ports:
            - "3306:3306"
        volumes: 
            - ./mysql:/var/lib/mysql
        networks:
            - nginx-php-mysql-node
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment: 
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: root
            MYSQL_PASSWORD: secret

    # node
    node-service:
        image: node:latest
        container_name: node-container
        volumes:
            - ./app:/var/www/project
        working_dir: /var/www/project
        networks:
            - nginx-php-mysql-node

        command: bash -c "npm run dev && npm run dev"
        ports:
            - "3000:3000"